apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluent-bit

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    namespace: fluent-bit
    version: 0.39.0
    valuesFile: values.yaml
    #includeCRDs: true
